[tool.black]
line-length = 100
target-version = ["py311","py312"]  # ajuste à ta version locale de Python

[tool.ruff]
line-length = 100
target-version = "py311"            # idem, ajuste si besoin (ex: "py312")
extend-exclude = ["venv", ".venv", "build", "dist"]
select = ["E","F","I","B","UP"]     # erreurs, fautes, imports, bonnes pratiques, upgrades
fix = true                          # autorise les corrections automatiques

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q --cov=src --cov-report=term-missing"
testpaths = ["tests"]
pythonpath = ["src"]
